#!/usr/bin/env python3
"""
NURA Edge — Offline Services (daily tips + wellness check-ins)

This reproduces two of NURA's real production services — the personalized daily
health tip and the daily wellness check-in — but running ENTIRELY on the local
quantized model, with no cloud and no internet.

In the full NURA platform these are generated by a hosted LLM (Groq/Bedrock).
Here the exact same prompts and patient-context logic run against the local
GGUF model, proving the whole service works offline on a clinic laptop.

The prompts are taken verbatim from the production backend so the offline
behaviour is faithful to the real product, not a re-imagination.

Usage:
  python rag/services.py tip
  python rag/services.py checkin
  python rag/services.py demo        # shows both, for the ADTC demo video
"""
from __future__ import annotations
import os, sys, subprocess, pathlib
from dataclasses import dataclass

sys.path.insert(0, str(pathlib.Path(__file__).parent))

os.environ.setdefault("HF_HUB_OFFLINE", "1")

from services_prompts import (
    DAILY_TIP_SYSTEM_PROMPT, CHECKIN_SYSTEM_PROMPT,
    POST_LOSS_TIP_SYSTEM_PROMPT, POST_LOSS_CHECKIN_SYSTEM_PROMPT,
)

ROOT       = pathlib.Path(__file__).parent.parent
MODEL_PATH = ROOT / "models" / "nura-q4_k_m.gguf"
LLAMA_CLI  = ROOT / "llama.cpp" / "build" / "bin" / "llama-cli"
SMS_LIMIT  = 155


# ── Patient model (minimal offline mirror of the backend's Patient) ──────────
@dataclass
class Patient:
    name: str
    week: int                 # gestational week
    risk_level: str = "low"   # low | medium | high
    age: int | None = None
    parity: int = 0
    channel: str = "app"      # app | sms
    language: str = "en"
    conditions: list[str] = None
    status: str = "active"    # active | post_loss

    def __post_init__(self):
        if self.conditions is None:
            self.conditions = []


# ── context builder (mirrors checkin_generator._build_context) ───────────────
def _lang_name(p: Patient) -> str:
    return {"en": "English", "fr": "French", "pt": "Portuguese"}.get(p.language, "English")


def _build_context(p: Patient) -> str:
    parts = [
        f"Patient name: {p.name}",
        f"Gestational age: week {p.week} of pregnancy",
        f"Risk level: {p.risk_level or 'not yet assessed'}",
        f"Age: {p.age or 'not provided'}",
        f"Number of prior births (parity): {p.parity}",
        f"Channel: {p.channel}",
        f"Active conditions / risk factors: {', '.join(p.conditions) if p.conditions else 'none flagged'}",
        f"Write the message in: {_lang_name(p)}",
    ]
    return "\n".join(parts)


# ── local LLM call (same role as llm_service.classify_message) ───────────────
def _run_local(system_prompt: str, context: str, max_tokens: int, temp: float) -> str:
    prompt = (
        f"<|im_start|>system\n{system_prompt}<|im_end|>\n"
        f"<|im_start|>user\n{context}<|im_end|>\n"
        f"<|im_start|>assistant\n"
    )
    out = subprocess.run(
        [str(LLAMA_CLI), "-m", str(MODEL_PATH),
         "-p", prompt, "-n", str(max_tokens), "-c", "1024", "-t", "8",
         "-ngl", "0", "-no-cnv", "-st", "--temp", str(temp),
         "--no-display-prompt"],
        capture_output=True, text=True,
        stdin=subprocess.DEVNULL,      # never wait for interactive input
    )
    return _clean(_strip_noise(out.stdout))


def _strip_noise(raw: str) -> str:
    """Remove llama-cli's banner / log lines that can leak into stdout,
    keeping only the model's generated text."""
    lines = raw.splitlines()
    keep = []
    for ln in lines:
        s = ln.strip()
        if not s:
            continue
        # skip banner art, build/log lines, command help, and the prompt echo
        if any(tok in s for tok in ("██", "▄▄", "build ", "model ", "ftype",
                                    "modalities", "available commands", "/exit",
                                    "/regen", "/clear", "/read", "/glob",
                                    "Loading model", "<|im_start|>", "<|im_end|>",
                                    "Exiting", "t/s")):
            continue
        keep.append(ln)
    return "\n".join(keep).strip()


def _clean(text: str) -> str:
    """Enforce the hard style rules a small model sometimes misses:
    no exclamation marks, no 'Today's tip:'-style preamble, trim to first
    clean sentence group. Keeps the model's content, fixes the format."""
    text = text.replace("!", ".")                       # rule: no exclamation marks
    # strip common preambles the rules forbid
    for pre in ("Today's tip:", "Tip:", "Check-in:", "Here is", "Here's"):
        if text.lower().startswith(pre.lower()):
            text = text[len(pre):].lstrip(" :-")
    # collapse any accidental double periods from the replace
    while ".." in text:
        text = text.replace("..", ".")
    return text.strip()


# ── the two services (mirror generate_daily_tip / generate_checkin) ──────────
def generate_daily_tip(p: Patient) -> str:
    if p.status == "post_loss":
        system = POST_LOSS_TIP_SYSTEM_PROMPT
        context = (f"Patient name: {p.name}\nChannel: {p.channel}\n"
                   "Situation: this patient has recently experienced a pregnancy loss.")
        max_tokens = 80 if p.channel == "sms" else 200
    else:
        system = DAILY_TIP_SYSTEM_PROMPT
        context = _build_context(p)
        max_tokens = 60 if p.channel == "sms" else 250

    tip = _run_local(system, context, max_tokens, temp=0.8)
    if p.channel == "sms" and len(tip) > SMS_LIMIT:
        tip = tip[:152] + "..."
    return tip


def generate_checkin(p: Patient) -> str:
    if p.status == "post_loss":
        system = POST_LOSS_CHECKIN_SYSTEM_PROMPT
        context = (f"Patient name: {p.name}\nChannel: {p.channel}\n"
                   "Situation: this patient has recently experienced a pregnancy loss.")
        max_tokens = 80 if p.channel == "sms" else 200
    else:
        system = CHECKIN_SYSTEM_PROMPT
        context = _build_context(p)
        max_tokens = 60 if p.channel == "sms" else 250

    msg = _run_local(system, context, max_tokens, temp=0.7)
    if p.channel == "sms" and len(msg) > SMS_LIMIT:
        msg = msg[:152] + "..."
    return msg


# ── demo patients (representative African maternal-health cases) ─────────────
DEMO_PATIENTS = [
    Patient(name="Amina", week=30, risk_level="high", age=34, parity=3,
            channel="sms", conditions=["hypertension", "history of pre-eclampsia"]),
    Patient(name="Grace", week=12, risk_level="low", age=24, parity=0,
            channel="app"),
    Patient(name="Fatou", week=20, risk_level="medium", age=29, parity=1,
            channel="sms", conditions=["severe anaemia"]),
]


def _patient_from_db(record: dict) -> Patient:
    """Build a Patient from a saved DB record so services can look patients up."""
    conditions = []
    if record.get("has_hypertension"):      conditions.append("hypertension")
    if record.get("has_diabetes"):          conditions.append("diabetes")
    if record.get("has_sickle_cell"):       conditions.append("sickle cell disease")
    if record.get("has_hiv"):               conditions.append("HIV-positive")
    if record.get("has_severe_anaemia"):    conditions.append("severe anaemia")
    if record.get("multiple_pregnancy"):    conditions.append("multiple pregnancy")
    if record.get("previous_preeclampsia"): conditions.append("history of pre-eclampsia")
    if record.get("previous_loss_count"):   conditions.append("history of pregnancy loss")
    return Patient(
        name=record["name"],
        week=record.get("weeks_pregnant_at_signup") or 1,
        risk_level=record.get("risk_level") or "low",
        age=record.get("age"),
        parity=record.get("parity") or 0,
        channel=record.get("channel") or "app",
        language=record.get("language") or "en",
        conditions=conditions,
        status=record.get("status") or "active",
    )


def _demo():
    print("\n" + "=" * 64)
    print("  NURA Edge — Offline Services Demo  (no cloud, no internet)")
    print("=" * 64)
    for p in DEMO_PATIENTS:
        cond = ", ".join(p.conditions) if p.conditions else "none"
        print(f"\n── {p.name} · week {p.week} · {p.risk_level}-risk · {p.channel.upper()} · conditions: {cond}")
        print(f"   DAILY TIP : {generate_daily_tip(p)}")
        print(f"   CHECK-IN  : {generate_checkin(p)}")
    print("\n" + "=" * 64)
    print("  All generated locally on the quantized model. Zero API calls.")
    print("=" * 64 + "\n")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "demo"
    # Optional 2nd arg = patient name to look up in the DB
    patient_name = sys.argv[2] if len(sys.argv) > 2 else None

    if cmd in ("tip", "checkin"):
        import db as _db
        _db.init_db()
        if patient_name:
            rec = _db.get_patient(patient_name)
            if not rec:
                print(f"No patient named '{patient_name}' in the database. "
                      f"Onboard her first:  python rag/onboarding.py")
                sys.exit(1)
            p = _patient_from_db(rec)
            pid = rec["id"]
        else:
            p = DEMO_PATIENTS[0]
            pid = None

        if cmd == "tip":
            msg = generate_daily_tip(p)
            print(msg)
            if pid:
                _db.log_message(pid, msg, message_type="tip", channel=p.channel)
        else:
            msg = generate_checkin(p)
            print(msg)
            if pid:
                _db.log_message(pid, msg, message_type="checkin", channel=p.channel)
    else:
        _demo()
